FROM docker:dind

RUN echo "nameserver 1.1.1.1" > /etc/resolv.conf && \
    echo "nameserver 8.8.8.8" >> /etc/resolv.conf && \
    apk add --no-cache bash make python3 py3-pip && \
    pip3 install --no-cache-dir docker-compose awscli