AWSTemplateFormatVersion: "2010-09-09"

Description: Network Infrastructure

Parameters:
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Target subnets for NAT Gateway
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Target VPC

Resources:
  # Private subnets
  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub ${AWS::Region}a
      CidrBlock: 172.31.48.0/24
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: Private-a
  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub ${AWS::Region}b
      CidrBlock: 172.31.49.0/24
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: Private-b
  PrivateSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub ${AWS::Region}c
      CidrBlock: 172.31.50.0/24
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: Private-c     

  # Route table for private subnets
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId
  PrivateSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnetA
  PrivateSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnetB
  PrivateSubnetCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnetC

  # Routes
  PrivateRouteTableDefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref PrivateRouteTable
      NatGatewayId: !Ref NatGateway

  # NAT Gateway
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !Sub ${ElasticIP.AllocationId}
      SubnetId:
        Fn::Select:
          - 0
          - !Ref PublicSubnets
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

# Export Private Subnets
Outputs:
  SubnetA:
    Description: Private subnet in AZ a
    Value: !Ref PrivateSubnetA
    Export:
      Name: private-subnet-a
  ubnetB:
    Description: Private subnet in AZ b
    Value: !Ref PrivateSubnetB
    Export:
      Name: private-subnet-b
  SubnetC:
    Description: Private subnet in AZ c
    Value: !Ref PrivateSubnetC
    Export:
      Name: private-subnet-c
    